namespace BetterTownOfUs
{
    public enum CustomRPC
    {
        SetJester = 60,
        SetCouple,
        SetMayor,
        SetSheriff,
        SetEngineer,
        SetSwapper,
        SetShifter,
        SetInvestigator,
        SetTimeLord,
        SetMedic,
        SetSeer,
        SetMorphling,
        SetCamouflager,
        SetExecutioner,
        SetTarget,
        SetSpy,
        SetSnitch,
        SetMiner,
        SetSwooper,
        SetJanitor,
        SetLycan,
        SetArsonist,
        SetAltruist,
        SetProphet,
        SetUndertaker,
        SetAssassin,
        SetUnderdog,
        SetTeleporter,
        SetConcealer,

        SetTorch,
        SetDiseased,
        SetFlash,
        SetTiebreaker,
        SetDrunk,
        SetBigBoi,
        SetButtonBarry,

        SetPhantom,
        PhantomDied,
        CatchPhantom,

        SetCrewmate,
        SetImpostor,


        LoveWin,
        GlitchWin,
        ArsonistWin,
        PhantomWin,
        JesterLose,
        ExecutionerLose,
        ShifterLose,
        GlitchLose,
        ArsonistLose,
        NobodyWins,
        PhantomLose,

        JanitorClean,
        LycanWolf,
        Wolf,
        FixLights,
        EngineerFix,
        SetExtraVotes,
        SetSwaps,
        Shift,
        Protect,
        AttemptSound,
        Investigate,
        Rewind,
        RewindRevive,
        Morph,
        Camouflage,
        VotedLover,
        Mine,
        Swoop,
        Douse,
        Ignite,
        AltruistRevive,
        BarryButton,
        Drag,
        Drop,
        AssassinKill,
        MissKill,
        Teleport,
        Conceal,

        SetGlitch,
        BypassKill,
        SetMimic,
        RpcResetAnim,
        SetHacked,

        ExecutionerToJester,


        Start,
        SyncCustomSettings,
        FixAnimation,

        AddMayorVoteBank
    }
}
